ava-labs/Simplex

- epoch.go
- epoch_test.go
- notarization.go
- notarization_test.go
- record_test.go
- recovery_test.go
Decouple NewNotarization and NewFinalization from epoch and create tests for both. Also updates the methods sort the signers by NodeID to ensure `FinalizationCertificates` & `Notarizations` are consistent between nodes.
> Separate Notarization/Finalization

- epoch_multinode_test.go
The test TestSimplexMultiNodeSimple spins up 4 Simplex instances by creating them and then triggerring a new block to be created.
Unfortunately, part of starting a new Simplex node is having it realize it's the leader of the first ever round, and proposing a block.
In our unit tests, triggers for block creations are controlled via a golang channel.
When starting a new Simplex instance that is the leader of the current round, it will block until the trigger for block creation is fed into the aforementioned golang channel.
Therefore, it is mandatory to load the block creation trigger before starting the instances.
Unfortunately, this has a nasty side-effect: The first block proposal sent from the leader of the first round, may get lost.
The reason is that Simplex protects itself from …
> Fix UT flake

- epoch.go
- epoch_multinode_test.go
- epoch_test.go
- recovery_test.go
- sched.go
- sched_test.go
When it is a node's turn to propose a block, it calls the BlockBuilder's BuildBlock method.
However, this method may take a long time to complete, and during this time, the Epoch instance
cannot process messages (since proposing a new block may be called indirectly via HandleMessage).
This commit adds an asynchronous task scheduler which the Epoch uses to register a callback to make itself propose the block after building it asynchronously.
> Build blocks asynchronously

- epoch_test.go
- notarization_test.go
- record_test.go
- recovery_test.go
Instead of instantiating the test signer in every test at the top most level, and rippling it downto where it is used, just instantiate it where we need it.
> Instantiate test signer on demand in tests

- epoch.go
- epoch_test.go
Votes from the block proposer are piggybacked by the block message.
The current code verifies them twice, so I removed the redundant processing.
> Remove redundant vote processing of piggybacked vote

- epoch_failover_test.go
- epoch_multinode_test.go
- epoch_test.go
- notarization_test.go
- recovery_test.go
- testutil/logger.go
- Fix caller skip (was wrong)
- Move it to its own package to be imported from both _test package and non _test package
- Put a better looking date and time format
- Add the name of the test to the logger so we understand which test it corresponds to
Code shamelessly copied from avalancheGo
> Improve logging for tests

- epoch.go
- epoch_multinode_test.go
- epoch_test.go
When building a block, we look at the latest round and build the round on top of it, only if we have already committed a block already.
However, since we notarize rounds asynchronously, we may advance to a new round before we commit a block.
We therefore need to use the rounds themselves as an indicator.
> Use correct sequence and metadata when building block

- epoch.go
- epoch_test.go
- monitor.go
- recovery_test.go
- testutil/logger.go
Couple small improvements
- No need to call `persistFinalizationCertifcate` when recovering from the WAL
- Fixed tests to reflect WAL(we would never add a fCert to the wal if its the next sequence to commit).
> Cleanup recovery from fCert in WAL

- encoding.go
- epoch.go
- epoch_failover_test.go
- epoch_multinode_test.go
- epoch_test.go
- metadata.go
- msg.go
- notarization.go
- record/consts.go
This commit adds agreement on empty blocks when a leader times out.
We write to WAL when:
- We time out on a round, so that when we recover we won't accept a proposal.
- We receive an empty notarization before we received a notarization.
Basic unit test where a node played by the test doesn't act in a timely manner,
and the node instantiated in the test then lobbies for an empty block notarization.
> Leader failover

- epoch.go
- epoch_test.go
- sched.go
This commit prevents re-execution of a block of the same round, twice or more.
This prevents two things:
- A leader sending a block twice to the same node
- A node executing a block twice by receiving one from the leader via the consensus agreement path, and also receiving one from the replication code path.
It works by introducing a wrapper around the existing scheduler, which tracks the round number of the block being executed.
This doesn't prevent the same block from being proposed by different nodes in different rounds.
>     Prevent re-execution of a block in the same round

- epoch.go
- epoch_failover_test.go
A node might be the last node among a quorum that times out. It therefore receives the empty votes before sending the empty vote itself, so it should check if it is possible to assemble an empty notarization right after sending the empty vote, because otherwise it might never get a trigger to check if an empty notarization can be assembled.
> Try to collect an empty notarization after sending an empty vote

- epoch.go
- epoch_test.go
- record_test.go
- replication_test.go
> Don't Send FutureFCertRequests if currently verifying proposal. 

- epoch.go
- epoch_failover_test.go
- epoch_test.go
This commit makes it that:
1) Nodes can accept a notarization of a block that they timed out on
2) Nodes will not vote on a block that they timed out on.
3) Nodes will not broadcast a finalization of a block that they accepted its notarization.
> Refuse finalizing a timed out round despite being notarized

- epoch.go
- epoch_test.go
We may receive a notarization message for a future round, and in that case - when we move to that round and finish verifying the proposal, we can just use it to advance to the next round.
> Store future notarization message

- .github/workflows/lint.yaml
- epoch.go
- epoch_failover_test.go
@yacovm, i know you are not a fan of having linters so early on in the dev process, but I find myself running `go fmt` often and it many unnecessary diffs in our PRs. I think go fmt is a very standard and basic lint check that would be helpful to add.
> Add Go Fmt action to CI

- epoch.go
- epoch_failover_test.go
- recovery_test.go
when the e.rounds map is populated but has no blocks with `notarizations` or `finalizations` the `metadata` function would panic on a `nil` dereference.
> Check if round exists before accessing fields in metadata

- replication.go
The previous code would have returned early if the lagging node requested had an `endSeq` of 0. Therefore, because `lastSequenceRequested` defaults to 0, we also need to check if `highestFcertReceived` is populated before exiting early.
> Update Collect Finalization Certificates to Properly Return Early

- api.go
- encoding.go
- epoch.go
- epoch_failover_test.go
- epoch_multinode_test.go
- epoch_test.go
- msg.go
- notarization_test.go
- record_test.go
- recovery_test.go
- replication_test.go
- util.go
- util_test.go
When we receive a block from the network, it should be verified before it can be persisted into stable storage.
Similarly, when we load a block from stable storage, there is no more need to verify it, as we had verified it before.
This commit makes the compiler enforce that a block received from the network cannot be persisted into stable storage before it has been verified.
> Distinguish between verified and unverified blocks

- epoch.go
- epoch_test.go
- util.go
- util_test.go
This commit makes sure that a QC only contains signers that are among the nodes the Epoch was initialized with. Similarly, it checks the QC is not signed twice or not signed by too few nodes.
This eases the implementation of a QC by the application, especially for naive implementations where the QC contains the public keys of the signers, and the Signers() method just returns a deterministic derivation of the aforementioned public keys.
> Make sure QC only contains authorized signers and is not signed twice

- epoch.go
- epoch_failover_test.go
Rather than deleting from `emptyVotes` immediately after persisting to the wal, we delete once the round has advanced enough. This is needed for replication, since nodes need to be able to retrieve `emptyNotarziation` when requested.  
Tthis PR also adds the same logic to the `rounds` map, as before `rounds` could have grown indefinitely.
> Delete Old Runtime Map Key/Values

- epoch_failover_test.go
- epoch_multinode_test.go
- epoch_test.go
the core problem was `runCrashAndRestartExecution` was being called too early. The test flakes occur when the crashed node clones the `WAL` before the original epoch finishes writing to it. 
Here's an example of when our node would stall. The `println` **"wal cloned"** is called right before we clone the wal. **Reboot started** is printed before `e.Start()` on the crashed node is called. Even after **Reboot started** is printed, the original epoch is still performing actions. 
```
wal cloned
=== RUN   TestEpochLeaderFailoverWithEmptyNotarization/TestEpochLeaderFailoverWithEmptyNotarization-with-crash#19
[03-04|15:38:48.817] DEBUG Simplex/epoch.go:1657 Wrote block to WAL {"test": "TestEpochLeaderFailoverWithEmptyNotarization", "node": 1, "round": 4, "size": 125, "digest": …
```
> Fix Flake in Failover Test

- epoch.go
- monitor.go
flake described in more detail in #133 
the solution is to ensure the previous task was executed before scheduling a new one.
> Fix monitor dropping tasks

- replication_test.go
avoids a flake where we check the lagging nodes metadata before waiting for the wal to be updated.
> Assert WAL before checking metadata

- epoch.go
- epoch_multinode_test.go
- monitor_test.go
- replication.go
- replication_test.go
- replication_timeout_test.go
- timeout_handler.go
- timeout_handler_test.go
- util.go
- util_test.go
This PR introduces a `TimeoutHandler`, that tracks outgoing replication requests and resends them once a timeout has occurred. 
The logic for handling incomplete requests is as follows
- we send out replication requests, and not the timeouts in `TimeoutHandler`
- when we receive a `ReplicationResponse` we check if the response data contains all the expected sequences
- if so, we can return early and remove the timeout task
- if not, we create new requests by figuring out the missing sequences and distributing them across nodes
This approach is nice because it keeps the logic fairly simple. However, because we only remove `1 TimeoutTask` every time we receive a response, it's possible we could send duplicate replication requests over the network. For example say we have 2 TimeoutTasks from …
> Resend Replication Requests After a Timeout

- metadata.go
- msg.go
We had many functions that performed the same serialization of the blockheader/protocol metadata structs. I moved out the common serialization into separate helper functions.
This helps AvalancheGo, where we re-implement this serialization when building blocks from bytes. It also allows a one-step switch to `asn1` instead of updating serialization in multiple places.
> Consolidate Metadata and Blockheader Serialization

- api.go
- encoding.go
- epoch.go
- epoch_test.go
- recovery_test.go
When a node crashes we should reverify the block on recovery, as verified blocks are stored in memory and should never be re-created from bytes.
> Add Block Verification During Wal Recovery

- api.go
- encoding.go
- epoch.go
- epoch_test.go
- recovery_test.go
- replication_request_test.go
So that we can pass in a context into the [block parser](https://github.com/ava-labs/avalanchego/pull/4009#discussion_r2178717248)
> Add Context to Deserializer API

- metadata.go
We store `FinalizationCertificates` in storage when we `Index` a block. We save the finalization as well as the quorum certificate in a single byte buffer(`[finalizationBytes][quorumCertificateBytes]`. When we retrieve the `fCert` from storage we need to know how many bytes are in the finalization(aka `BlockHeaderLen`).
> Expose BlockHeader Length

- epoch.go
more of stylistic pr, but I think it makes more sense to only call `assembleFinalization` when we have done all the pre-checking for the `finalizedVotes`
> additional checking in maybeCollectFinalization vs assemble

- epoch.go
- epoch_multinode_test.go
- replication.go
- replication_request_test.go
- replication_timeout_test.go
> Resend ReplicationRequest If Finalization Is Expected But Not Received 

- epoch.go
LatestRound will always exist, but response.LatestRound only gets set if needed
> Use Response.LatestRound

- epoch.go
- replication_timeout_test.go
I could add this for notarizations, but it seems like we are not planning on re[-requesting notarizations](https://github.com/ava-labs/Simplex/issues/214#issuecomment-3232314089)?
This solves #187
> Resend replication requests for finalized blocks that fail to verify

- fuzz.sh
This commit makes the fuzz tests be skipped in 4 out of 5 runs.
> Skip fuzz tests in most CI runs

- epoch.go
- epoch_failover_test.go
If we have scheduled waiting for pending transactions and then the timeout expired, in the meantime we may have advanced to a new round.
While a mechanism exists to abort such a situation, it is invoked too early and a race can occur in which we advance to a new round while we are scheduling the task of the timeout itself.
This commit checks if we have advanced the round right before the timeout triggers, which happens under a lock.
Fixes issue https://github.com/ava-labs/Simplex/issues/231
> Abort timing out on a stale round

- replication_test.go
`TestRebroadcastingWithReplication` puts every node in a replication state. This is because we block all finalization from propogating over the network. Once we allow a finalization for a future round to be broadcasted, all nodes start replicating/rebroadcasting the missing finalizations. 
The flake was cause because `ReplicationRequests` and `FinalizeVote` messages could be delivered in unknown order. If a `ReplicationRequest` was processed before a `finalizeVote` message, that node would send a `QuorumRound` without a finalization. That quorum round would be rejected by the receiving node(since we expect a finalization), and the receiving node would schedule another replication request after a timeout.
We would never advance the time so the timeout is never triggered and thus the test …
> Fix Flake in TestRebroadcastingWithReplication

- epoch.go
We currently cannot replicate empty rounds using our message schema, so this code should be removed.
> Remove redundant code

- epoch.go
When we receive a block, we schedule it to be processed:
- Verify the vote
- Execute/Verify the block
- Write to to the WAL etc.
We may receive a finalization in the meanwhile, and we therefore store it as a future message to be processed.
Since we received a finalization for a future round, this might trigger the replication process. In order to prevent us from initiating replication needlessly, Simplex would store the pending block message as a future message, and then when a finalization is received, it would look if a block message exists among the future messages, as an indication for the block being processed.
This works, but creates an annoying downside - the block message is still in the future messages, and it may get picked up once more by anything that optimistically calls …
> Mark block as being processed, not as a future block

- blacklist.go
- blacklist_test.go
This commit prevents to redeem a node in a given orbit if the node has been lastly suspected in the same orbit.
The intent is to prevent a situation where a node momentarily loses connection in the round it is supposed to propose a block, it is then blacklisted after a few rounds, and the nodes then redeem it when they build blocks notarized on top of the blocks where it is redeemed in. However, since the nodes use the finalized blocks and not the notarized blocks to know whether to time out immediately on a blacklisted node or not, they might have not finalized the block where it has been redeemed in by time, and therefore they immediately time out. Since they immediately time out, the node is then blacklisted again, as it has been redeemed right before it had a chance to propose a …
> Blacklist: Prevent redeeming a node suspected in the same orbit
